import type { Metadata } from "next";
import { Archivo, Archivo_Black } from "next/font/google";
import { cn } from "@/lib/utils";
import styles from "./layout.module.css";
import "./globals.css";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const archivoBlack = Archivo_Black({
  variable: "--font-archivo-black",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "BoxFlow",
  description: "Gestión de socios y membresías para tu gimnasio.",
};

// Deliberately a plain, hand-written props type rather than Next's
// generated `LayoutProps<"/">` — that type only exists once `.next/types`
// has been generated by a prior `next dev`/`next build`, which makes
// `tsc --noEmit` fail on a clean checkout/CI before any build has run.
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(archivo.variable, archivoBlack.variable, "dark", styles.html)}
    >
      <body className={styles.body}>{children}</body>
    </html>
  );
}
