import { pgTable, uuid, date, integer, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { tenants } from "./tenants";
import { classSchedules } from "./class-schedules";

/**
 * One concrete date of a recurring ClassSchedule slot (T-20260826-011) —
 * e.g. "class_schedules row for Mondays 18:00" + "2026-08-25" = the actual
 * Monday-the-25th class. This is what capacity/waitlist/attendance attach
 * to, never the recurring slot itself: a slot's capacity resets every
 * week, it doesn't accumulate across occurrences.
 *
 * Deliberately NOT batch-generated by a job for every future date of every
 * slot (that would explode this table with rows for classes nobody ever
 * booked and needs periodic infrastructure this project doesn't have).
 * Instead, a row here is created lazily — on the first reservation, or the
 * first explicit capacity override, for a given (classScheduleId, date).
 * Until then, that date's occurrence is purely conceptual: its effective
 * capacity is just classSchedules.capacity and it has zero reservations,
 * which callers can compute without a row existing yet — see
 * app/api/v1/schedules/[id]/occurrences/route.ts's GET.
 */
export const classOccurrences = pgTable(
  "class_occurrences",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    classScheduleId: uuid("class_schedule_id")
      .notNull()
      .references(() => classSchedules.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    // Overrides classSchedules.capacity for this one date, if set (e.g. an
    // instructor is out and the sub can only handle fewer people). Null =
    // inherit the slot's default.
    capacity: integer("capacity"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("class_occurrences_schedule_date_unique").on(
      table.tenantId,
      table.classScheduleId,
      table.date,
    ),
  ],
);

export type ClassOccurrence = typeof classOccurrences.$inferSelect;
export type NewClassOccurrence = typeof classOccurrences.$inferInsert;
